DROP TABLE IF EXISTS prouni.concession CASCADE;
DROP TABLE IF EXISTS prouni.course CASCADE;
DROP TABLE IF EXISTS prouni.institution CASCADE;
DROP TABLE IF EXISTS census.city CASCADE;
DROP TABLE IF EXISTS census.census CASCADE;
DROP SCHEMA IF EXISTS prouni CASCADE;
DROP SCHEMA IF EXISTS census CASCADE;
